source 'https://rubygems.org'

gem 'breakpoint'
gem 'wdm', '~> 0.1' if Gem.win_platform?
gem 'rake'
gem 'jekyll'

group :development, :test do
  gem "github-pages", group: :jekyll_plugins
  gem 'jekyll-redirect-from', '~> 0.14.0'
  gem 'jekyll-sitemap', '~> 1.2.0'
  gem 'jekyll-toc', '~> 0.6.0'
  gem 'jekyll-paginate-v2'
  gem 'jekyll-gist', '~> 1.5.0'
  gem 'jekyll-remote-theme', '~> 0.3.0'
  gem 'jemoji', '~> 0.10.0'
  gem 'html-proofer', '~> 3.9.0'
  #gem 'rake', '~> 12.3.0'
  gem 'jekyll-figure', :git => 'https://github.com/mmistakes/jekyll-figure.git'
  gem 'jekyll-algolia', '>= 1.4.7'
  gem 'jekyll-tagging-related_posts'
  gem 'jekyll-include-cache'
end

